config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider', to: 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  resource :messages do
    collection do
      post 'reply'
      post 'remind'
      post 'initiate'
    end
  end

  root to: "site#index"
  get 'parents/index' => "parents#index"
  get 'parents/sitters' => "parents#sitters"
  get '/sitters' => 'site#sitters'
  get '/privacypolicy' => "site#privacypolicy"
  get '/termsofservice' => "site#termsofservice"

  namespace :api do
    namespace :v1 do
      resources :appointments, only: [:index, :create, :destroy, :update]
      resources :sitters, only: [:index, :create, :destroy, :update]
    end
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/parent.rb
class Parent < ActiveRecord::Base
end

app/models/sitter.rb
class Sitter < ActiveRecord::Base
  has_many :appointments

  validates :name, uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |sitter|
      sitter.provider = auth.provider
      sitter.uid = auth.uid
      sitter.name = auth.info.name
      sitter.oauth_token = auth.credentials.token
      sitter.oauth_expires_at = Time.at(auth.credentials.expires_at)
      return sitter
    end
  end

end

app/controllers/api/v1/appointments_controller.rb
class Api::V1::AppointmentsController < Api::V1::BaseController

  def index
    respond_with Appointment.all
  end

  def create
    respond_with :api, :v1, Appointment.create(appointment_params)
  end

  def update
    appointment = Appointment.find(params["id"])
    appointment.update_attributes(appointment_params)
    respond_with appointment, json: appointment
  end

  def destroy
    respond_with Appointment.destroy(params[:id])
  end

  private

    def appointment_params
      params.require(:appointment).permit(:id, :description, :start_time, :end_time, :sitter_id, :reminder_sent)
    end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/sitters_controller.rb
class Api::V1::SittersController < Api::V1::BaseController
  # before_action :set_sitter, only: [:show, :edit, :update, :destroy]

  def index
    sitters = Sitter.all
    render json: sitters.as_json(only: [:id, :name, :phone, :email]), status: :ok
  end

  def create
    respond_with :api, :v1, Sitter.create(sitter_params)
  end

  def update
    sitter = Sitter.find(params["id"])
    sitter.update_attributes(sitter_params)
    respond_with sitter, json: sitter
  end

  def destroy
    respond_with Sitter.destroy(params[:id])
  end

  private
    def sitter_params
      params.require(:sitter).permit(:id, :name, :phone, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :current_sitter

  # @super_user = http_basic_authenticate_with name: "me", password: "@home"

  def current_sitter
    @current_sitter ||= Sitter.find(session[:sitter_id]) if session[:sitter_id]
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  def reply
    boot_twilio
    message_body = params["Body"]
    from_number = params["From"]
    # find sitter with that phone number
    sitter = Sitter.find_by(phone: from_number[2..11])
    # find appointment by reply message.
    appointment = Appointment.find(message_body.to_i)

    #if there is already sitter_id, tell sitter appointment is covered, and don't update sitter id.
    if appointment.sitter_id
      covering_sitter = Sitter.find(appointment.sitter_id)
      if sitter.name == covering_sitter.name
        body = "You already accepted this appointment. Thanks again!"
      else
        body = "Thank you so much for offering, #{sitter.name}! However, #{covering_sitter.name} is already helping me on this one."
      end

      @client.account.messages.create(
        from: ENV["TWILIO_NUMBER"],
        to: from_number,
        body: body
      )
    else # send confirmation and update sitter_id
      @client.account.messages.create(
        from: ENV["TWILIO_NUMBER"],
        to: from_number,
        body: "Thank you so much for helping me out, #{sitter.name}. You're on the schedule. I'll send you a reminder the day before. If you'd like to check out your schedule before then, please visit www.mybabysittingschedule.com "
      )
      appointment.update_attribute(:sitter_id, sitter.id)
      # also send confirmation to Parent (me!!)
      @client.account.messages.create(
        from: ENV["TWILIO_NUMBER"],
        to: ENV["PARENT_NUMBER"],
        body: "#{sitter.name} is taking care of an appointment for you."
      )
    end
  end

  def initiate
    boot_twilio
    sitter_number = params['phone']
    date = DateTime.parse(params['start_time'])
    body = "Hello, this is Guinevere. I was hoping you might be available for watching Brendan? Details below. #{date.strftime("%B %-d at %l%P")}: #{params['description']}. If you can do this, please reply with the following number: #{params['appointment_id']} "
    @client.account.messages.create(
      from: ENV["TWILIO_NUMBER"],
      to: sitter_number,
      body: body,
    )

    redirect_to parents_index_path

  end

  def remind
    boot_twilio
    # logger.debug "sent reminder!"

    # TODO fix time zone issue with Time.now grrrr

    appointments = Appointment.where(start_time: ((Time.now-8.hours)..((Time.now - 8.hours) + 1.day)))

    appointments.each do |appointment|
      if (appointment.sitter_id) && (appointment.reminder_sent == false)
        if Sitter.find(appointment.sitter_id)
          sitter = Sitter.find(appointment.sitter_id)
        else
          next
        end
        body = "Hello, this is Guinevere, sending you a reminder about babysitting Brendan tomorrow. Details: #{appointment.start_time.strftime("%B %-d at %l%P")}: #{appointment.description}. Thanks again and see you soon!"
        @client.account.messages.create(
          from: ENV["TWILIO_NUMBER"],
          to: sitter.phone,
          body: body,
        )
        appointment.update_attribute(:reminder_sent, true)
      end
    end
  end

  private

  def boot_twilio
    account_sid = ENV["TWILIO_ACCOUNT_SID"]
    auth_token = ENV["TWILIO_AUTH_TOKEN"]
    @client = Twilio::REST::Client.new account_sid, auth_token
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController

  http_basic_authenticate_with name: ENV["PARENT_NAME"], password: ENV["PARENT_PASSWORD"]

  def index; end

  def sitters; end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    sitter = Sitter.from_omniauth(env["omniauth.auth"])
    if Sitter.find_by(name: sitter.name)
      session[:sitter_id] = Sitter.find_by(name: sitter.name).id
    else
      if sitter.save
        session[:sitter_id] = sitter.id
      else
        flash[:notice] = "Something went wrong with your login. Please contact the site administrator for help if the problem persists."
      end
    end
    redirect_to root_path
  end

  def destroy
    session[:sitter_id] = nil
    redirect_to root_path
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  force_ssl if: :ssl_configured?

  def ssl_configured?
    !Rails.env.development?
  end
  
  def login; end

  def index
    @error = flash[:notice]
    @current_sitter ||= Sitter.find(session[:sitter_id]) if session[:sitter_id]
  end

  def privacypolicy; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sitters_helper.rb
module SittersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBabysittingSchedule</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet">
</head>
<body>
  <div class="wrapper">
    <header>
      <div class="site-header">
        <h1>My Babysitting Schedule</h1>
      </div>
    </header>

    <div class="separator"></div>

    <div>
      <%= yield %>
    </div>

    <div class="push"></div>
  </div>
  <div class="separator"></div>
  <footer>
    <div class="site-footer">
      &copy; 2017 by Guinevere Saenger
      <%=link_to "Privacy Policy", privacypolicy_path, class: "sign-in-spacing" %>
      <%=link_to "Terms of Service", termsofservice_path, class: "sign-in-spacing" %>
    </div>
  </footer>

</body>
</html>

app/views/parents/index.html.erb
<%= link_to "Manage Sitters", parents_sitters_path, class: 'links' %>

<%= react_component 'Main' %>

app/views/parents/sitters.html.erb
<%= link_to "Back to Schedule", parents_index_path, class: 'links' %>

<%= react_component 'SitterList'  %>

app/views/site/index.html.erb
<% if @error %>
  <h3><%= @error %></h3>
<% end %>

<div>
  <% if current_sitter %>
    <div class="sign-in-spacing">
      Signed in as <%= current_sitter.name %>

      <%= link_to "Sign out", signout_path, id: "sign-out" %>
    </div>
  <% else %>
    <p class="sign-in-spacing">Please login to see the schedule.</p>
    <p class="sign-in-spacing"><%= link_to "Sign in with Google", "/auth/google_oauth2", class: "sign-in" %></p>
    <p class="sign-in-spacing"><%= link_to "Sign in with Facebook", "/auth/facebook", class: "sign-in" %></p>
    <p class="sign-in-spacing"><%= link_to "I am the Parent", parents_index_path, class: "sign-in" %></p>
<% end %>
</div>

<% if @current_sitter %>
  <%= react_component 'Main', {currentSitter: @current_sitter}  %>
<% end %>

app/views/site/privacypolicy.html.erb
<h5> Privacy Policy</h5>
<p>
This site is a student project, designed for personal use by its creator, Guinevere Saenger.
This application will store a user's name upon login, and their phone number and email by personal request.
I will not share your information with anyone for any reason.
</p>
<%= link_to "Back", root_path %>

app/views/site/termsofservice.html.erb
<h5>Terms of Service</h5>
<p>
This site is a student project, designed for personal use by me, Guinevere Saenger.
Its main purpose is to create appointments and send corresponding SMS messages to user's phones.
If your phone number is in this database, it means you at one point gave me verbal permission to manually enter your phone number into my database. If you wish to be removed from the database, please contact me at guineveresaenger(at)yahoo(dot)com.
For further information on the code, see the GitHub repository on<a href="https://github.com/guineveresaenger/sit-in-peace">Github</a>.
</p>
<%= link_to "Back", root_path %>